Use quoteattr for attribute serialization
For Python 3.14 compat, which failed with:

```
  File "/usr/lib/python3.14/site-packages/roboticstoolbox/tools/xacro/xmlutils.py", line 124, in fixed_writexml
TypeError: _write_data() missing 1 required positional argument: 'attr'
```